/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Poppins"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body:    ['"Poppins"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono:    ['ui-monospace', '"SF Mono"', 'Menlo', 'Consolas', 'monospace'],
      },
      colors: {
        paper: 'var(--color-paper)',
        'paper-2': 'var(--color-paper-2)',
        'paper-3': 'var(--color-paper-3)',
        surface: 'var(--color-surface)',
        ink: 'var(--color-ink)',
        'ink-2': 'var(--color-ink-2)',
        muted: 'var(--color-muted)',
        rule: 'var(--color-rule)',
        'rule-2': 'var(--color-rule-2)',
        accent: {
          pink:   'var(--color-accent-pink)',
          violet: 'var(--color-accent-violet)',
          ink:    'var(--color-accent-ink)',
          focus:  'var(--color-focus)',
        },
        card: {
          purple: 'var(--color-card-purple)',
          pink:   'var(--color-card-pink)',
          blue:   'var(--color-card-blue)',
          mint:   'var(--color-card-mint)',
          amber:  'var(--color-card-amber)',
        },
        on: {
          purple: 'var(--color-on-purple)',
          pink:   'var(--color-on-pink)',
          blue:   'var(--color-on-blue)',
          mint:   'var(--color-on-mint)',
          amber:  'var(--color-on-amber)',
        },
        feedback: {
          correct:      'var(--color-correct)',
          'correct-text': 'var(--color-correct-text)',
          'correct-bg': 'var(--color-correct-bg)',
          wrong:        'var(--color-wrong)',
          'wrong-text': 'var(--color-wrong-text)',
          'wrong-bg':   'var(--color-wrong-bg)',
          urgent:       'var(--color-urgent)',
        },
      },
      boxShadow: {
        xs:    'var(--shadow-xs)',
        sm:    'var(--shadow-sm)',
        md:    'var(--shadow-md)',
        lg:    'var(--shadow-lg)',
        glow:  'var(--shadow-glow-pink)',
        'glow-violet': 'var(--shadow-glow-violet)',
      },
      backgroundImage: {
        'accent-gradient': 'linear-gradient(135deg, var(--color-accent-pink) 0%, var(--color-accent-violet) 100%)',
      },
      animation: {
        'fade-in':    'fade-in 0.5s var(--ease-out) forwards',
        'slide-up':   'slide-up 0.4s var(--ease-out) forwards',
        'scale-in':   'scale-in 0.3s var(--ease-out) forwards',
        'shake':      'shake 0.5s cubic-bezier(.36,.07,.19,.97)',
        'bounce-in':  'bounce-in 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'float':      'float 3s ease-in-out infinite',
        'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
      },
      keyframes: {
        'fade-in':   { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        'slide-up':  { '0%': { transform: 'translateY(20px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        'scale-in':  { '0%': { transform: 'scale(0.94)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        'shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-4px)' },
          '20%, 40%, 60%, 80%':       { transform: 'translateX(4px)' },
        },
        'bounce-in': {
          '0%':  { transform: 'scale(0)',    opacity: '0' },
          '50%': { transform: 'scale(1.15)' },
          '100%':{ transform: 'scale(1)',    opacity: '1' },
        },
        'float':       { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
        'pulse-soft':  { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.7' } },
      },
    },
  },
  plugins: [],
};
